# name: CI
# on:
#   pull_request:
#     branches: [develop]

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - name: Use nodeJS
#         uses: actions/setup-node@v1
#         with:
#           node-version: "12.x"
#       - run: npm ci
#       - run: npm install --save-dev --save-exact prettier
#       - run: npm run format:check
#       - run: npm test -- --coverage
#         env:
#           CI: true


name: CI
on:
  pull_request:
    branches: [develop]
  push:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use nodeJS
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - run: npm install
      - run: npm run format:check
      - run: npm test -- --coverage
        env:
          CI: true
      - name: Build project
        if: github.event_name == 'push'
        run: npm run build
      # - run: npm install --global surge
      # - name: Deploy to Staging
      #   if: github.event_name == 'push'
      #   run: surge
      #     OR
      - name: Deploy to Staging
        if: github.event_name == 'push'
        run: npx surge --project ./build --domain pointless-throat.surge.sh #npx will install and run surge here
        env:
          SURGE_LOGIN: ${{ secrets.SURGE_LOGIN }}
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
