name: CI
on: push
  # pull_request:
  #   branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use nodeJS
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - run: npm ci
      - run: sudo npm run format:check
      - run: npm test -- --coverage
        env:
          CI: true
      

  